// A real delayed worker packet must not undo a user's pause; opening a file must quiet audio.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium,webkit} from '../.tools/browser/node_modules/playwright/index.mjs';
const engine=process.argv[2],output=process.argv[3],base=process.argv[4]??'http://127.0.0.1:8766';if(!output||fs.existsSync(output))throw new Error('New evidence directory required');fs.mkdirSync(output,{recursive:true});
const browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,args:engine==='chromium'?['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']:[]});
const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce',acceptDownloads:true});
await context.addInitScript(()=>{
 const NativeAudio=window.AudioContext;window.AudioContext=class extends NativeAudio{constructor(...args){super(...args);window.testAudio=this;}};
 const NativeWorker=window.Worker;window.Worker=class extends NativeWorker{constructor(...args){super(...args);let callback=null;Object.defineProperty(this,'onmessage',{get:()=>callback,set:value=>callback=value});this.addEventListener('message',event=>{
  if(window.holdOneFrame&&event.data.type==='frame'&&event.data.running){window.holdOneFrame=false;window.heldRealFrame=true;window.releaseRealFrame=()=>{callback?.call(this,event);window.afterOldFrame={running:document.body.dataset.running,button:document.querySelector('#pause').textContent,materialRunning:document.body.dataset.materialRunning};window.heldRealFrame=false;};return;}
  callback?.call(this,event);
 });}};
});
const page=await context.newPage();page.setDefaultTimeout(30000);const errors=[];page.on('pageerror',e=>errors.push(e.message));const report={engine,base,errors};
try{
 await page.goto(base+'/choir.html');await page.waitForFunction(()=>document.body.dataset.ready==='true'&&document.querySelector('#choir-clock').dataset.time!==undefined);await page.locator('#enter-sound').click();await page.waitForFunction(()=>document.body.dataset.materialRunning==='true');await page.locator('.choir-voice[data-body="1"]').click();await page.keyboard.down('Space');await page.waitForFunction(()=>Number(document.querySelector('#choir-clock').dataset.time)>3);await page.keyboard.up('Space');
 await page.evaluate(()=>window.holdOneFrame=true);await page.waitForFunction(()=>window.heldRealFrame===true);await page.locator('#pause').click();await page.waitForFunction(()=>document.body.dataset.running==='false');report.delayedFrame=await page.evaluate(()=>{window.releaseRealFrame();return window.afterOldFrame;});await page.waitForFunction(()=>document.body.dataset.materialRunning==='false');
 const [download]=await Promise.all([page.waitForEvent('download'),page.locator('#save').click()]);await download.saveAs(output+'/encounter.json');assert.equal(await download.failure(),null);
 await page.locator('#pause').click();await page.waitForFunction(()=>document.body.dataset.materialRunning==='true'&&window.testAudio.state==='running');const start=Number(await page.locator('#choir-clock').getAttribute('data-time'));await page.locator('.choir-voice[data-body="1"]').click();await page.keyboard.down('Space');await page.waitForFunction(t=>Number(document.querySelector('#choir-clock').dataset.time)>t+1,start);await page.keyboard.up('Space');await page.locator('#open').setInputFiles(output+'/encounter.json');await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Encounter opened'));await page.waitForTimeout(150);report.openedWhilePlaying=await page.evaluate(()=>({audioState:window.testAudio.state,running:document.body.dataset.running,materialRunning:document.body.dataset.materialRunning,time:document.querySelector('#choir-clock').dataset.time}));
 await page.locator('#sound').click();await page.waitForFunction(()=>document.body.dataset.sound==='false');await page.locator('#sound').click();await page.waitForFunction(()=>document.body.dataset.sound==='true');report.soundPreferenceWhilePaused=await page.evaluate(()=>({audioState:window.testAudio.state,running:document.body.dataset.running}));
 await page.locator('#pause').click();await page.waitForFunction(()=>document.body.dataset.materialRunning==='true'&&window.testAudio.state==='running');report.soundResumesWithMaterial=true;
 report.pauseIntentSurvivesOldFrame=report.delayedFrame.running==='false'&&report.delayedFrame.button==='Resume';report.importSuspendsSound=report.openedWhilePlaying.audioState==='suspended';report.pausedSoundPreferenceStaysSuspended=report.soundPreferenceWhilePaused.audioState==='suspended'&&report.soundPreferenceWhilePaused.running==='false';fs.writeFileSync(output+'/report.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));assert.deepEqual(errors,[]);assert(report.pauseIntentSurvivesOldFrame&&report.importSuspendsSound&&report.pausedSoundPreferenceStaysSuspended);
}finally{await browser.close();}
