// Exercise the geometric work, true crossing ties, frozen export and recovery.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {chromium,webkit} from '../.tools/browser/node_modules/playwright/index.mjs';
import {screenshotEvidence} from './browser_screenshot.mjs';
const engine=process.argv[2]??'chromium',output=process.argv[3],base=process.argv[4]??'http://127.0.0.1:8766';if(!output||fs.existsSync(output))throw Error('New evidence directory required');fs.mkdirSync(output,{recursive:true});
const browser=await(engine==='webkit'?webkit:chromium).launch({headless:true,args:engine==='chromium'?['--no-sandbox']:[]}),context=await browser.newContext({viewport:{width:1440,height:1100},acceptDownloads:true,reducedMotion:'reduce'}),page=await context.newPage();page.setDefaultTimeout(30000);const errors=[],consoleErrors=[];page.on('pageerror',e=>errors.push(e.message));const evidence=screenshotEvidence(page,engine,consoleErrors);const result={engine,base,errors,consoleErrors,screenshotInstrumentationWarnings:evidence.warnings};
const set=async value=>page.locator('#origin-shift').evaluate((input,value)=>{input.value=String(value);input.dispatchEvent(new Event('input',{bubbles:true}));},value);
try{
 const raw=fs.readFileSync('site/assets/generated/observer-origin-v1.json'),data=JSON.parse(raw);assert.equal(crypto.createHash('sha256').update(raw).digest('hex'),'e8010a136443c2bd0b3854965aade4dd7def03d612d1b3f2dab529c962e8e886');
 await page.goto(base+'/observer.html');await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.evaluate(()=>document.fonts.ready);assert.equal(await page.locator('body').getAttribute('data-own'),'18');assert.equal(await page.locator('#origin-table tr').count(),24);
 await evidence.capture(page,{path:output+'/opening.jpg',type:'jpeg',quality:84});await evidence.capture(page.locator('#moving-origin'),{path:output+'/original.jpg',type:'jpeg',quality:86});
 result.crossings=[];
 for(let i=0;i<data.events.length;i++){
  await page.locator('#origin-next').click();const event=data.events[i],state=await page.locator('body').evaluate(b=>({...b.dataset}));assert(Math.abs(Number(state.alpha)-event.alpha)<1e-14);assert.equal(Number(state.own),18+i);assert.equal(Number(state.ties),1);
  const row=page.locator('#origin-table tr').nth(event.history);assert.equal(await row.getAttribute('data-tied'),'true');assert.equal(await row.locator('td').first().textContent(),event.at.map(j=>data.orders[j]).join(' / ')+' (tie)');result.crossings.push({alpha:Number(state.alpha),own:Number(state.own),tied:Number(state.ties),history:data.orders[event.history]});
 }
 assert(await page.locator('#origin-next').isDisabled());await evidence.capture(page.locator('#moving-origin'),{path:output+'/last-crossing.jpg',type:'jpeg',quality:86});
 await page.locator('#origin-shift').focus();await page.keyboard.press('End');assert.equal(await page.locator('body').getAttribute('data-own'),'24');await page.keyboard.press('ArrowLeft');assert(Math.abs(Number(await page.locator('body').getAttribute('data-alpha'))-.99)<1e-14);await page.keyboard.press('Shift+ArrowLeft');assert(Math.abs(Number(await page.locator('body').getAttribute('data-alpha'))-.989)<1e-14);result.keyboard=true;
 // Freeze an export at click time even if the visitor moves while fonts arrive.
 const captured=data.events[3].alpha;await page.locator('#origin-reset').click();for(let i=0;i<4;i++)await page.locator('#origin-next').click();assert.equal(Number(await page.locator('body').getAttribute('data-alpha')),captured);let releaseFont;let held=false;await page.route('**/assets/generated/serif.woff2',async route=>{held=true;await new Promise(resolve=>releaseFont=resolve);await route.continue();});
 const downloadPromise=page.waitForEvent('download');await page.locator('#origin-export').click();await page.waitForTimeout(100);assert(held);await set(.9);releaseFont();const download=await downloadPromise;await download.saveAs(output+'/measured-position.svg');assert.equal(await download.failure(),null);await page.unroute('**/assets/generated/serif.woff2');
 const exported=fs.readFileSync(output+'/measured-position.svg','utf8');result.export=await page.evaluate(({text,captured,data})=>{const doc=new DOMParser().parseFromString(text,'image/svg+xml');if(doc.querySelector('parsererror'))throw Error('Invalid exported SVG');const metadata=JSON.parse(doc.querySelector('metadata').textContent),circles=[...doc.querySelectorAll('.origin-current')],expected=data.rows.map(row=>66+(row.raw_projection+captured*(row.aligned_projection-row.raw_projection)+.16)/1.32*(1100-132));return {metadataAlpha:metadata.alpha,own:metadata.own_matches,ties:metadata.tied_readings,dataSha256:metadata.data_sha256,pointError:Math.max(...circles.map((circle,i)=>Math.abs(Number(circle.getAttribute('cx'))-expected[i]))),embeddedFonts:(doc.querySelector('style').textContent.match(/data:font\/woff2;base64,/g)||[]).length,licensePresent:metadata.font_license.length>1000};},{text:exported,captured,data});assert.equal(result.export.metadataAlpha,captured);assert.equal(result.export.own,21);assert.equal(result.export.ties,1);assert(result.export.pointError<1e-12&&result.export.embeddedFonts===2&&result.export.licensePresent);
 const exportPage=await context.newPage();await exportPage.goto('about:blank');await exportPage.setContent('<!doctype html><html><head><title>Export proof</title></head><body><img alt="The exported measured print"></body></html>');await exportPage.locator('img').evaluate(async(image,url)=>{image.src=url;await image.decode();},'data:image/svg+xml;base64,'+Buffer.from(exported).toString('base64'));await exportPage.screenshot({path:output+'/export.jpg',type:'jpeg',quality:85,fullPage:true});await exportPage.close();
 await page.locator('#origin-reset').click();await page.locator('#origin-play').click();await page.waitForFunction(()=>Number(document.body.dataset.alpha)>.015);await page.locator('#origin-play').click();const paused=await page.locator('body').getAttribute('data-alpha');await page.waitForTimeout(200);assert.equal(await page.locator('body').getAttribute('data-alpha'),paused);result.pauseExact=true;
 await page.locator('#origin-play').click();await page.waitForFunction(()=>document.body.dataset.playing==='false'&&document.body.dataset.alpha==='1',null,{timeout:35000});assert.equal(await page.locator('body').getAttribute('data-own'),'24');result.completePassage=true;
 await page.setViewportSize({width:393,height:852});await page.locator('#origin-reset').click();await page.locator('#moving-origin').scrollIntoViewIfNeeded();await evidence.capture(page,{path:output+'/mobile.jpg',type:'jpeg',quality:86});result.mobileOverflow=await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth);assert.equal(result.mobileOverflow,0);assert.equal(await page.locator('#origin-drawing').getAttribute('viewBox'),'0 0 500 820');
 await page.evaluate(fs.readFileSync('.tools/browser/node_modules/axe-core/axe.min.js','utf8'));result.accessibility=await page.evaluate(async()=>{const r=await axe.run(document,{runOnly:{type:'tag',values:['wcag2a','wcag2aa','wcag21aa']}});return{violations:r.violations.map(v=>({id:v.id,impact:v.impact,nodes:v.nodes.map(n=>n.target)})),incomplete:r.incomplete.map(v=>v.id)};});assert.deepEqual(result.accessibility.violations,[]);
 await page.route('**/assets/generated/observer-origin-v1.json',route=>route.fulfill({status:200,contentType:'application/json',body:'{"version":1}'}));await page.reload();await page.waitForFunction(()=>document.body.dataset.ready==='false');assert(await page.locator('#origin-export').isDisabled());assert(!(await page.locator('#origin-retry').isHidden()));await page.unroute('**/assets/generated/observer-origin-v1.json');await page.locator('#origin-retry').click();await page.waitForFunction(()=>document.body.dataset.ready==='true');assert.equal(await page.locator('body').getAttribute('data-own'),'18');result.changedDataRejectedAndRetryRecovered=true;
 assert.deepEqual(errors,[]);assert.deepEqual(consoleErrors,[]);fs.writeFileSync(output+'/report.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}catch(error){result.failure=error.message;result.status=await page.locator('#origin-status').textContent().catch(()=>null);await evidence.capture(page,{path:output+'/failure.jpg',type:'jpeg',quality:80}).catch(()=>{});fs.writeFileSync(output+'/failure.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));throw error;}finally{await browser.close();}
