// Exercise the extracted two-act installation with external connectivity disabled.
import fs from 'node:fs';
import assert from 'node:assert/strict';
import {chromium} from '../.tools/browser/node_modules/playwright/index.mjs';
const output=process.argv[2],origin=process.argv[3]??'http://127.0.0.1:8089';
if(!output||fs.existsSync(output))throw new Error('Supply a new evidence directory');fs.mkdirSync(output,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader'],proxy:{server:'http://127.0.0.1:9',bypass:'127.0.0.1,localhost'}});
const context=await browser.newContext({viewport:{width:1440,height:1080},reducedMotion:'reduce',acceptDownloads:true});
const page=await context.newPage();page.setDefaultTimeout(45000);const errors=[],external=[],requests=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin===origin){requests.push(url.pathname);await route.continue();}else{external.push(url.href);await route.abort('internetdisconnected');}});
const result={origin,errors,externalDependencies:external};
const jsonDownload=async(button,name)=>{const [d]=await Promise.all([page.waitForEvent('download'),page.locator(button).click()]);const path=output+'/'+name+'.json';await d.saveAs(path);assert.equal(await d.failure(),null);return JSON.parse(fs.readFileSync(path,'utf8'));};
async function film(selector,button,seconds,duration){await page.locator(button).click();await page.locator(selector).evaluate((v,t)=>{if(v.readyState>=1)v.currentTime=t;else v.addEventListener('loadedmetadata',()=>v.currentTime=t,{once:true});},seconds);await page.waitForFunction(({selector,seconds})=>{const v=document.querySelector(selector);return v.videoWidth===1920&&v.currentTime>seconds+.7&&!v.paused&&!v.seeking;},{selector,seconds});const state=await page.locator(selector).evaluate(v=>{const r={time:v.currentTime,duration:v.duration,width:v.videoWidth,height:v.videoHeight,src:v.currentSrc};v.pause();return r;});assert.equal(state.duration,duration);assert.equal(new URL(state.src).origin,origin);return state;}
try{
 await page.goto(origin+'/');await page.waitForFunction(()=>document.querySelector('#choir-downloads a').textContent.includes('Film master'));
 const book=await page.locator('#notebook .arrow-link').getAttribute('href');assert.equal(book,'/assets/generated/a-choir-of-absences-notebook.pdf');const response=await page.request.head(origin+book);assert.equal(response.status(),200);assert.equal(Number(response.headers()['content-length']),2035676);result.secondBookBytes=Number(response.headers()['content-length']);
 result.secondFilm=await film('#ensemble-film','#enter-ensemble',248,288);
 for(const name of ['encounter','after','source']){await page.locator(`[data-choir-sculpture="${name}"]`).click();await page.waitForFunction(()=>document.querySelector('#choir-sculpture-canvas').dataset.state==='ready');assert.equal(await page.locator('#download-choir-sculpture').getAttribute('href'),`/assets/generated/choir-${name}.glb`);await page.locator('#choir-sculpture-canvas').press('ArrowLeft');await page.keyboard.press('Escape');}
 result.secondSculptures=3;
 await page.goto(origin+'/choir.html');await page.waitForFunction(()=>document.body.dataset.ready==='true'&&document.querySelector('#choir-clock').dataset.time!==undefined);await page.locator('#enter-sound').click();await page.waitForFunction(()=>document.body.dataset.running==='true');await page.locator('.choir-voice[data-body="1"]').click();await page.keyboard.down('Space');await page.waitForFunction(()=>Number(document.querySelector('#choir-clock').dataset.time)>10);await page.keyboard.up('Space');
 result.choir={memory:await page.locator('.choir-voice').evaluateAll(b=>b.map(v=>Number(v.dataset.memory))),audioPeak:Number(await page.locator('body').getAttribute('data-audio-peak'))};assert(result.choir.memory[1]>.1&&result.choir.memory[0]>.001&&result.choir.audioPeak>.0001);
 await page.locator('#pause').click();await page.waitForFunction(()=>document.body.dataset.materialRunning==='false');const saved=await jsonDownload('#save','choir-before-reload');await page.waitForFunction(()=>document.querySelector('#recovery').dataset.saved==='true');await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent.startsWith('Recovered the recent encounter'));assert.deepEqual(await jsonDownload('#save','choir-after-reload'),saved);result.choir.exactRecovery=true;
 await page.goto(origin+'/witness.html');await page.waitForFunction(()=>document.body.dataset.ready==='true');await page.locator('#play-question').click();await page.waitForFunction(()=>document.body.dataset.playing==='true'&&Number(document.body.dataset.position)>1);await page.locator('[data-body="G"]').click();await page.waitForFunction(()=>document.body.dataset.listener==='G'&&document.body.dataset.playing==='true'&&Number(document.body.dataset.position)>2);await page.locator('button[data-history="after"]').click();result.witness={listener:'G',time:Number(await page.locator('body').getAttribute('data-position')),difference:await page.locator('#difference').textContent()};assert.equal(result.witness.difference,'4.694 Hz');await page.locator('#play-question').click();
 await page.goto(origin+'/first-act.html');await page.waitForFunction(()=>document.querySelectorAll('#download-list a').length===12);result.firstFilm=await film('#main-film','#enter-film',370,432);
 const firstBook=await page.locator('#notebook .arrow-link').getAttribute('href');assert.equal(firstBook,'/assets/generated/palimpsest-complete-notebook.pdf');const firstResponse=await page.request.head(origin+firstBook);assert.equal(firstResponse.status(),200);assert.equal(Number(firstResponse.headers()['content-length']),10477076);result.firstBookBytes=10477076;
 await page.goto(origin+'/atlas.html');await page.waitForFunction(()=>!document.querySelector('#probe-play').disabled);assert.equal(await page.locator('.history-glyph').count(),120);await page.locator('#probe-play').click();await page.waitForFunction(()=>document.querySelector('#probe-0').currentTime>1);result.atlas=await page.locator('#probe-0').evaluate(a=>({time:a.currentTime,duration:a.duration,source:a.currentSrc}));await page.locator('#probe-play').click();
 await page.goto(origin+'/pressure.html');await page.waitForFunction(()=>document.body.dataset.pressureReady==='true');await page.getByRole('button',{name:'Allow for pressure',exact:true}).click();assert.equal(await page.locator('#identified-count').textContent(),'881 / 960');const [drawing]=await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'Keep this pair as SVG',exact:false}).click()]);await drawing.saveAs(output+'/pressure.svg');assert.equal(await drawing.failure(),null);result.pressureExport=true;
 await page.goto(origin+'/instrument.html');await page.waitForFunction(()=>document.querySelector('#live-sculpture').dataset.state==='ready'&&document.querySelector('#live-sculpture').dataset.time!==undefined);await page.locator('#begin-sound').click();await page.waitForFunction(()=>document.body.dataset.running==='true');await page.keyboard.down('q');await page.waitForFunction(()=>Number(document.querySelector('#live-sculpture').dataset.time)>4);await page.keyboard.up('q');result.firstInstrument=await page.locator('#live-sculpture').evaluate(c=>({...c.dataset}));assert(Number(result.firstInstrument.memory)>.1&&Number(result.firstInstrument.audioPeak)>.005);
 await page.locator('#pause-material').click();await page.waitForFunction(()=>document.querySelector('#live-sculpture').dataset.materialRunning==='false'&&document.querySelector('#recovery-note').dataset.saved==='true');const paused=await page.locator('#live-sculpture').evaluate(c=>({...c.dataset}));await page.waitForFunction(time=>Math.abs(Number(document.querySelector('#recovery-note').dataset.time)-Number(time))<.00001,paused.time);await page.reload();await page.waitForFunction(()=>Number(document.querySelector('#live-sculpture').dataset.time)>4);const recovered=await page.locator('#live-sculpture').evaluate(c=>({...c.dataset}));assert.equal(recovered.time,paused.time);assert.equal(recovered.memory,paused.memory);assert.equal(recovered.wear,paused.wear);result.firstInstrument.exactSummaryRecovery=true;
 await page.setViewportSize({width:393,height:852});await page.goto(origin+'/');await page.screenshot({path:output+'/mobile.jpg',type:'jpeg',quality:80});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth-innerWidth),0);result.mobileOverflow=0;
 assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await page.unroute('**/*');const blocked=await page.evaluate(async()=>{try{await fetch('https://example.com/',{mode:'no-cors',signal:AbortSignal.timeout(3000)});return false;}catch(error){return error.name==='TypeError';}});assert(blocked);result.externalConnectivityBlocked=true;result.localRequests=[...new Set(requests)].sort();result.scope='Extracted installation, dead external proxy and loopback-only server. Actual films, recorded listening, live synthesis, state recovery, sculpture viewing and drawing export. No perceptual audition or physical-device claim.';
 fs.writeFileSync(output+'/report.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));
}catch(error){result.failure=error.message;await page.screenshot({path:output+'/failure.jpg',type:'jpeg',quality:75}).catch(()=>{});fs.writeFileSync(output+'/failure.json',JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));throw error;}finally{await browser.close();}
