"""Restore the analytical record, reproduce every result and rebuild the vector print."""
import argparse
from datetime import datetime,timezone
import json
from pathlib import Path
import tempfile
from studio.preserve import sha256
from studio.verify_choir_download import restore_record,download
from studio.verify_choir_edition import run_module


def verify(root,proof):
    path=root/'palimpsest-quiet-choir-edition.json';edition=json.loads(path.read_text())
    for item in edition['files']:
        assert Path(item['name']).name==item['name'];p=root/item['name'];assert p.stat().st_size==item['bytes'] and sha256(p)==item['sha256'],p
    checks={n:d for d,n in (line.split('  ',1) for line in (root/'palimpsest-checksums.sha256').read_text().splitlines())}
    assert checks=={**{r['name']:r['sha256'] for r in edition['files']},path.name:sha256(path)}
    expected=json.loads((root/'quiet-choir-record-manifest.json').read_text());assert expected['source_commit']==edition['source_commit']
    restored=restore_record(root,proof,expected,'quiet-choir-record.tar.gz','quiet-choir-record-manifest.json');assert restored['files']==edition['scientific_archive_files']
    run_module('studio.choir_decay_bound',['--output','research/rebuilt-decay.json'],proof,'decay-rebuild')
    original=json.loads((proof/'research/choir-decay-bound-003.json').read_text());rebuilt=json.loads((proof/'research/rebuilt-decay.json').read_text())
    for item in (original,rebuilt):item.pop('verified_utc')
    assert original==rebuilt,'Numerical reconstruction differs'
    run_module('studio.choir_decay_figure',['--output','artwork/rebuilt-decay'],proof,'figure-rebuild')
    figures={}
    for name in ('quiet-choir.pdf','quiet-choir.svg'):
        p=proof/'artwork/rebuilt-decay'/name;assert p.read_bytes()==(root/name).read_bytes(),name;figures[name]=sha256(p)
    return {'source_commit':edition['source_commit'],'assets':len(edition['files'])+2,'restored':restored,'all_numerical_results_exact_except_timestamp':True,'byte_identical_rebuilt_figures':figures}


def main(args):
    out=Path(args.report)
    if out.exists():raise FileExistsError(out)
    downloads=[]
    with tempfile.TemporaryDirectory(prefix='quiet-choir-proof-',dir='backups') as temporary:
        base=Path(temporary)
        if args.receipt:
            receipt=json.loads(Path(args.receipt).read_text());assert receipt['repository']=='bernietorfen/palimpsest';assert sum(r['bytes'] for r in receipt['assets'])<100_000_000
            root=base/'download';root.mkdir()
            for item in receipt['assets']:downloads.append(download(item,root,'v2.3.0'))
        else:root=Path(args.edition)
        result=verify(root,base/'restored')
    result.update(verified_utc=datetime.now(timezone.utc).isoformat(),execution_host='RunPod',public_downloads=downloads,temporary_files_removed=True,scope='Every asset and restored member hashed, all exact certificates and numerical cross-checks rerun from the restored record, PDF and SVG regenerated byte for byte. Existing prepared runtime; no fresh dependency installation claim.')
    out.write_text(json.dumps(result,indent=2)+'\n');print(json.dumps(result),flush=True)


if __name__=='__main__':
    p=argparse.ArgumentParser();p.add_argument('--edition',default='artwork/quiet-choir-edition-001');p.add_argument('--receipt');p.add_argument('--report',required=True);main(p.parse_args())
